# Generated by Django 5.1.5 on 2025-02-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tin_hoc_tre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listening',
            name='status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
