# Generated by Django 5.1.5 on 2025-02-20 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tin_hoc_tre', '0003_alter_listening_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(null=True)),
                ('grade', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('skill', models.TextField(null=True)),
                ('file', models.FileField(null=True, upload_to='files/documents/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(max_length=1000, null=True)),
                ('comment_counter', models.IntegerField(null=True)),
                ('down', models.ManyToManyField(null=True, related_name='document_down', to='tin_hoc_tre.bio')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_level', to='tin_hoc_tre.level')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Document_auth', to='tin_hoc_tre.bio')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_document_user', to='tin_hoc_tre.bio')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmt_document', to='tin_hoc_tre.document')),
            ],
        ),
        migrations.CreateModel(
            name='Document_emoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts_document_emoji', to='tin_hoc_tre.document')),
                ('emoji', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emoji_document_emoji', to='tin_hoc_tre.emoji')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_document_emoji', to='tin_hoc_tre.bio')),
            ],
        ),
        migrations.CreateModel(
            name='have_buy_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.FloatField(null=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_check', to='tin_hoc_tre.document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Document_buyer', to='tin_hoc_tre.bio')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.CharField(max_length=1000)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('comment_counter', models.IntegerField()),
                ('down', models.ManyToManyField(related_name='post_down', to='tin_hoc_tre.bio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_auth_related', to='tin_hoc_tre.bio')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('status', models.CharField(max_length=1000)),
                ('down', models.ManyToManyField(related_name='comment_post_down', to='tin_hoc_tre.bio')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_post_user_related', to='tin_hoc_tre.bio')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_post_related', to='tin_hoc_tre.post')),
            ],
        ),
        migrations.CreateModel(
            name='Post_emoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emoji_post_emoji', to='tin_hoc_tre.emoji')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts_post_emoji', to='tin_hoc_tre.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_post_emoji', to='tin_hoc_tre.bio')),
            ],
        ),
    ]
