# Generated by Django 5.1.5 on 2025-03-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tin_hoc_tre', '0005_remove_document_down_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='bio',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnail/'),
        ),
    ]
