from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path('accounts/login', views.Login, name="a_login"),
    path('accounts/sign/up/', views.Signup, name="signup"),
    path('logout/', views.log_out, name="log_out"),
    path("check/", views.check, name="check"),
    path("create/speaking/scripts/", views.create_speaking_scripts_AI,
         name="create_speaking_scripts_AI"),
    path("create/listening/", views.create_listening_AI,
         name="create_listening_AI"),
    path("create/writting/", views.create_writting_AI, name="create_writting_AI"),
    path("create/reading/", views.create_reading_AI, name="create_reading_AI"),
    path("workspace/speaking/scripts/", views.my_speaking_scripts_workspace,
         name="my_speaking_scripts_workspace"),
    path("workspace/writting/", views.my_writting_workspace,
         name="my_writting_workspace"),
    path("workspace/reading/", views.my_reading_workspace,
         name="my_reading_workspace"),
    path("workspace/listening/", views.my_listening_workspace,
         name="my_listening_workspace"),
    path("view/speaking/scripts/<int:id>", views.speaking_scripts_view,
         name="speaking_scripts_view"),
    path("view/reading/<int:id>", views.reading_view,
         name="reading_view"),
    path("view/listening/<int:id>", views.listening_view,
         name="listening_view"),
    path("view/writting/<int:id>", views.writting_view,
         name="writting_view"),
    path("emoji/speaking/scripts/<int:id>/emo_id/<int:emoji_id>", views.speaking_scripts_emoji,
         name="speaking_scripts_emoji"),
    path("emoji/reading/<int:id>/emo_id/<int:emoji_id>", views.reading_emoji,
         name="reading_emoji"),
    path("emoji/listening/<int:id>/emo_id/<int:emoji_id>", views.listening_emoji,
         name="listening_emoji"),
    path("emoji/writting/<int:id>/emo_id/<int:emoji_id>", views.writting_emoji,
         name="writting_emoji"),
    path("change/status/speaking/scripts/<int:id>", views.change_status_speaking_scripts,
         name="change_status_speaking_scripts"),
    path("change/status/reading/<int:id>", views.change_status_reading,
         name="change_status_reading"),
    path("change/status/listening/<int:id>", views.change_status_listening,
         name="change_status_listening"),
    path("change/status/writting/<int:id>", views.change_status_writting,
         name="change_status_writting"),
    path("result/speaking/scripts/<int:id>", views.speaking_result_view,
         name="speaking_scripts_result_view"),
    path("result/reading/<int:id>", views.reading_result_view,
         name="reading_result_view"),
    path("result/listening/<int:id>", views.listening_result_view,
         name="listening_result_view"),
    path("result/writting/<int:id>", views.writting_result_view,
         name="writting_result_view"),
    path("comment/speaking/scripts/<int:id>", views.speaking_scripts_view,
         name="speaking_scripts_comment"),
    path("comment/reading/<int:id>", views.reading_comment,
         name="reading_comment"),
    path("comment/listening/<int:id>", views.listening_comment,
         name="listening_comment"),
    path("comment/writting/<int:id>", views.writting_comment,
         name="writting_comment"),
    path("submit/speaking/scripts/<int:id>", views.speaking_submit,
         name="speaking_scripts_submit"),
    path("submit/reading/<int:id>/number/<int:number>", views.reading_submit,
         name="reading_submit"),
    path("submit/listening/<int:id>/number/<int:number>", views.listening_submit,
         name="listening_submit"),
    path("submit/writting/<int:id>", views.writting_submit,
         name="writting_submit"),
    path("status/change/speaking/<int:id>", views.speaking_status_change,
         name="speaking_status_change"),
    path("status/change/reading/<int:id>", views.reading_status_change,
         name="reading_status_change"),
    path("status/change/listening/<int:id>", views.listening_status_change,
         name="listening_status_change"),
    path("status/change/writting/<int:id>", views.writting_status_change,
         name="writting_status_change"),
    path("result/list/speaking/<int:id>", views.speaking_list_result_view,
         name="speaking_list_result_view"),
    path("result/list/reading/<int:id>", views.reading_list_result_view,
         name="reading_list_result_view"),
    path("result/list/listening/<int:id>", views.listening_list_result_view,
         name="listening_list_result_view"),
    path("result/list/writting/<int:id>", views.writting_list_result_view,
         name="writting_list_result_view"),
    path("my/profile/", views.my_profile, name="my_profile"),
    path("user/<int:id>", views.user_profile, name="user_profile"),
    path("download/listening/<int:id>", views.download_listening_file,
         name="download_listening_file"),
    path("download/audio/<int:id>", views.download_audio_file,
         name="download_audio_file"),
    path("download/transcript/<int:id>", views.download_transcript_file,
         name="download_transcript_file"),
    path("download/speaking/scripts/<int:id>", views.download_speaking_scripts_file,
         name="download_speaking_scripts_file"),
    path("post/", views.post_list_view, name="post_view"),
    path("document/", views.document_list_view, name="document_list_view"),
    path("listening/", views.listening_list_view, name="listening_list_view"),
    path("writting/", views.writting_list_view, name="writting_list_view"),
    path("reading/", views.reading_list_view, name="reading_list_view"),
    path("speaking/scripts/", views.speaking_scripts_list_view,
         name="speaking_scripts_list_view"),
    path("create/post/", views.post_create, name="post_create"),
    path("create/document/", views.document_create, name="create_document"),
    path("comment/document/<int:id>",
         views.document_comment, name="document_comment"),
    path("comment/post/<int:id>", views.post_comment, name="comment_post"),
    path("emoji/document/<int:id>/emo_id/<int:emoji_id>",
         views.document_emoji, name="document_emoji"),
    path("emoji/post/<int:id>/emo_id/<int:emoji_id>",
         views.post_emoji, name="post_emoji"),
    path("document/<int:id>", views.document_view, name="document_view"),
    path("change/status/post/<int:id>", views.change_status_post,
         name="change_status_post"),
    path("change/status/document/<int:id>", views.change_status_document,
         name="change_status_document"),
    path("staff/post/", views.staff_post_list, name="staff_post_view"),
    path("staff/document/", views.staff_document_list,
         name="staff_document_list_view"),
    path("staff/document/view/<int:id>",
         views.staff_document_view, name="staff_document_view"),
    path("improve/writting/", views.improve_writting, name="improve_writting"),
    path("improve/listening/", views.improve_listening, name="improve_listening"),
    path("improve/reading/", views.improve_reading, name="improve_reading"),
    path("improve/speaking/", views.improve_speaking, name="improve_speaking"),
]
